### ISSUE TITLE
add instructions for building

### ISSUE THREAD

**Issue by ghost** [pabennett/glblox#5]
please add instructions for building, for osx

**Comment by max107** [comment]
`lib/build.sh`:

``` sh
g++ -std=c++0x -fPIC -c main.cpp -o glblox.o -framework OpenGL -lglut -lGLEW
g++ -fPIC -shared -Wl -shared -o glblox.so glblox.o -framework OpenGL -lglut -lGLEW
```

but my 10.11.4 mac don't recogize version 400 shader. Good luck :)

**Comment by Honghe** [comment]
@max107
I have encountered this problem too on `Ubuntu 14.04 64bit Intel i5 cpu`.

```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    'shaders/main.fragment'
  File "/home/honhe/Downloads/volume_render/glblox/shader.py", line 39, in openfiles
    program.use()
  File "/home/honhe/Downloads/volume_render/glblox/shader.py", line 160, in use
    shader.compile()
  File "/home/honhe/Downloads/volume_render/glblox/shader.py", line 97, in compile
    raise CompileError(self.getInfoLog())
shader.CompileError: 0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

```

Any Good idea to solve this problem?
Thanks!

**Comment by max107** [comment]
@Honghe i don't know how to fix it. My mac also not supported v4 glsl.

> GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

**Comment by fesoliveira014** [comment]
@Honghe Try changing the shaders' #version from 400 to 300, this should work. Each shader starts with this directive.

**Comment by Honghe** [comment]
@fesoliveira014 Which file to config? Thanks!

**Comment by fesoliveira014** [comment]
@Honghe , go to shaders directory and change the first line of each file from "#version 400" to "#version 300". I don't know if the author uses any feature present on glsl 4.00, but he shouldn't since he isn't doing anything fancy lol
